apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextjs-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "nextjs-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
